USE users;
CREATE TABLE Users (
  id BIGINT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id),
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255));

CREATE TABLE TimeNotes (
  id BIGINT NOT NULL AUTO_INCREMENT, PRIMARY KEY(id),
  userId BIGINT NOT NULL,
  timestamp TIMESTAMP NOT NULL,
  message VARCHAR(255),
  FOREIGN KEY (userId)
    REFERENCES Users(id),
  INDEX IND_USER_PERIOD(userId, timestamp)
);

